#!/usr/bin/env python3
"""Generate figures for D_sim_validation appendix.

Uses exp1_results.npz and exp2_results.npz from data/sim_validation/
(regenerated by paper/ram/scripts/exp1_short_horizon_prediction.py
 and paper/ram/scripts/exp2_long_horizon_prediction.py).

Output: supplementary/figures/sim_val_*.png
"""

import sys
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR    = _SCRIPT_DIR.parent.parent.parent / "data" / "sim_validation"
OUT_DIR     = _SCRIPT_DIR.parent / "figures"

FIG_SINGLE_COL = (3.5, 2.5)
FIG_DOUBLE_COL = (7.16, 3.5)
DT = 0.05

plt.rcParams.update({
    "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8,
    "xtick.labelsize": 7, "ytick.labelsize": 7, "legend.fontsize": 7,
    "figure.dpi": 150, "savefig.dpi": 300, "savefig.bbox": "tight",
    "axes.grid": True, "grid.alpha": 0.25,
})

ST_SHORT = [r"$x$", r"$\dot{x}$", r"$\theta$", r"$\dot{\theta}$"]
ST_UNITS = ["(m)", "(m/s)", "(rad)", "(rad/s)"]
ST_LAB   = [f"{s} {u}" for s, u in zip(ST_SHORT, ST_UNITS)]
C_BLUE  = "#1f77b4"
C_RED   = "#d62728"
C_GREEN = "#2ca02c"


def load_exp2():
    """Analytical best vs WorldModel from exp2, h=5..600."""
    data = np.load(DATA_DIR / "exp2_results.npz", allow_pickle=True)
    horizons = [5, 10, 20, 50, 100, 200, 300, 400, 600]
    return {
        "horizons": np.array(horizons),
        "h_sec":    np.array(horizons) * DT,
        "ana_term": np.array([data[f"Analytical_best_h{h}_terminal_mae"] for h in horizons]),
        "wm_term":  np.array([data[f"WorldModel_LSTM_h{h}_terminal_mae"] for h in horizons]),
        "ana_tot":  np.array([data[f"Analytical_best_h{h}_total_mae"] for h in horizons]),
        "wm_tot":   np.array([data[f"WorldModel_LSTM_h{h}_total_mae"] for h in horizons]),
    }


def load_exp1_traj():
    """Load traj MAE for ablation models from exp1 at h=50."""
    data = np.load(DATA_DIR / "exp1_results.npz", allow_pickle=True)
    h = 50
    out = {}
    key_map = [
        ("Bare (tau=0.06)", "Bare_tau=0.06"),
        ("+tau=0.15",       "+tau=0.15"),
        ("+Delay (1 step)", "+Delay_1_step"),
        ("+Delay+Obs filter", "+Delay+Obs_filter"),
    ]
    for label, key in key_map:
        k = f"{key}_h{h}_traj_mae"
        if k in data:
            out[label] = data[k]
    return out


# ---- FIGURE 1: Error Growth Curves (4-panel) ----

def fig_error_growth(d):
    fig, axes = plt.subplots(2, 2, figsize=FIG_DOUBLE_COL)
    axes = axes.flatten()
    hs = d["h_sec"]
    for col in range(4):
        ax = axes[col]
        ax.plot(hs, d["ana_term"][:, col], "-o", color=C_BLUE,
                lw=1.2, ms=3.5, label="Analytical (best)", zorder=3)
        ax.plot(hs, d["wm_term"][:, col], "-s", color=C_RED,
                lw=1.2, ms=3.5, label="World Model (LSTM)", zorder=3)
        ax.set_title(ST_LAB[col], fontsize=8)
        ax.set_xlabel("Prediction horizon (s)")
        ax.set_ylabel("Terminal MAE")
        ax.legend(fontsize=6, loc="upper left")
    plt.suptitle("Open-Loop Prediction Accuracy vs. Prediction Horizon",
                 fontsize=10, y=1.01)
    plt.tight_layout()
    fig.savefig(OUT_DIR / "sim_val_error_growth.png")
    plt.close(fig)
    print("  -> sim_val_error_growth.png")


# ---- FIGURE 2: Crossover Ratio ----

def fig_crossover_ratio(d):
    ratio = d["wm_tot"] / d["ana_tot"]
    fig, ax = plt.subplots(1, 1, figsize=FIG_SINGLE_COL)
    ax.plot(d["h_sec"], ratio, "-D", color=C_GREEN, lw=1.5, ms=5, zorder=3)
    ax.axhline(1.0, color="gray", lw=0.8, ls="--", label="Equal (ratio = 1)")
    ax.fill_between(d["h_sec"], ratio, 1.0, where=(ratio < 1.0),
                    color=C_GREEN, alpha=0.1, label="WM better")
    ax.set_xlabel("Prediction horizon (s)")
    ax.set_ylabel("WM / Analytical MAE ratio")
    ax.set_title("World Model vs Analytical: Accuracy Ratio", fontsize=9)
    ax.legend(fontsize=7, loc="lower right")
    ax.set_ylim(0.45, 1.05)
    for h, r, hs in zip(d["horizons"], ratio, d["h_sec"]):
        if h in [5, 50, 200, 600]:
            ax.annotate(f"{r:.2f}", xy=(hs, r), xytext=(hs + 1.5, r + 0.03),
                        fontsize=6, color=C_GREEN, ha="center")
    plt.tight_layout()
    fig.savefig(OUT_DIR / "sim_val_crossover_ratio.png")
    plt.close(fig)
    print("  -> sim_val_crossover_ratio.png")


# ---- FIGURE 3: Pipeline Waterfall ----

def fig_waterfall_pipeline(pipeline):
    names = list(pipeline.keys())
    totals = np.array([pipeline[n].sum() for n in names])
    n = len(names)
    fig, ax = plt.subplots(figsize=FIG_SINGLE_COL)
    deltas = [totals[0]] + [totals[i] - totals[i-1] for i in range(1, n)]
    colors = ["#aaaaaa"] + [C_GREEN if d < 0 else C_RED for d in deltas[1:]]
    ax.bar(range(n), totals, color=colors, alpha=0.85, edgecolor="black", lw=0.5, width=0.65)
    for i in range(1, n):
        delta_pct = -deltas[i] / totals[0] * 100
        ax.annotate(f"-{delta_pct:.0f}%", xy=(i, totals[i]),
                    xytext=(0, -14), textcoords="offset points",
                    fontsize=6, ha="center", color=C_GREEN)
    ax.set_xticks(range(n))
    ax.set_xticklabels(names, fontsize=6)
    ax.set_ylabel("Trajectory MAE (sum over 4 channels)")
    ax.set_title("Pipeline Ablation: Marginal Contribution (h=50, 2.5 s)", fontsize=8)
    plt.tight_layout()
    fig.savefig(OUT_DIR / "sim_val_waterfall_pipeline.png")
    plt.close(fig)
    print("  -> sim_val_waterfall_pipeline.png")


# ---- MAIN ----

if __name__ == "__main__":
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading exp2 (analytical vs WM, h=5..600)...")
    d2 = load_exp2()

    print("Loading exp1 ablation data (h=50)...")
    pipeline = load_exp1_traj()

    print("\nGenerating figures...")
    fig_error_growth(d2)
    fig_crossover_ratio(d2)
    fig_waterfall_pipeline(pipeline)

    # Print table data
    RANGES = [1.553, 1.8, 0.162, 1.0]
    key_horizons = [5, 50, 200, 600]
    print("\n  LaTeX: Analytical vs WM terminal MAE (normalized %):")
    for h in key_horizons:
        idx = list(d2["horizons"]).index(h)
        ana = d2["ana_term"][idx]
        wm  = d2["wm_term"][idx]
        ap = ana / RANGES * 100
        wp = wm / RANGES * 100
        print(f"  h={h*DT:.1f}s: Ana=({ap[0]:.0f}%, {ap[1]:.0f}%, {ap[2]:.0f}%, {ap[3]:.0f}%)")
        print(f"            WM=({wp[0]:.0f}%, {wp[1]:.0f}%, {wp[2]:.0f}%, {wp[3]:.0f}%)")
        gap = (wp - ap) / np.abs(ap) * 100
        print(f"            gap=({gap[0]:+.0f}%, {gap[1]:+.0f}%, {gap[2]:+.0f}%, {gap[3]:+.0f}%)")

    print("\n  LaTeX: Pipeline traj MAE at h=50:")
    for name in pipeline:
        v = pipeline[name]
        print(f"  {name}: x={v[0]:.4f} xd={v[1]:.4f} th={v[2]:.5f} thd={v[3]:.4f} total={v.sum():.4f}")

    print("\nDone. All figures in", OUT_DIR)
